techfromsage/talis-cdk-constructs

lib/cdn-site-hosting/cdn-site-hosting-construct.ts, lib/cdn-site-hosting/cdn-site-hosting-props.ts, lib/cdn-site-hosting/cdn-site-hosting-with-dns-construct.ts, test/cdn-site-hosting/cdn-site-hosting-construct.test.ts, test/cdn-site-hosting/cdn-site-hosting-with-dns-construct.test.ts
Extends the existing setup to allow multiple assets to be provided, with granular control over their properties for things like 'cache control'.
In the old days, you specified only `sources` and everything cached in the CDN got invalidated on deployment; now you can instead specify `sourcesWithDeploymentOptions`, which permits more granular control over the deployment invalidation.
A full, working example is part of the current work for user-utils-app:
https://github.com/talis/user-utils-app/pull/218/files#diff-1a22218de1adb65f49f030fa5552eaf8424ff321d3dc696df4cb7a70f2ffbf19R38-R102
=> Asset invalidation control

lib/authenticated-api/authenticated-api.ts, lib/authenticated-api/route-lambda-props.ts, lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/authenticated-api/authenticated-api.test.ts, test/lambda-worker/lambda-worker.test.ts
https://github.com/talis/platform/issues/5074
This PR makes changes to the `authenticated-api` construct and `lambda-worker` construct now that we are trying to use them outside of the examples within the project.
=> fix: changes to LambdaWorker and AuthenticatedAPI as we start to use them for real

examples/container-lambda-worker/lib/container-lambda-worker-stack.ts, lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/lambda-worker/lambda-worker.test.ts
When creating a container lambda worker the entrypoint to the container needs to be specified as the command to run when starting the docker container.
This change makes this a required property when creating a container lambda worker.
=> fix: require docker command to be passed to lambda

lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/lambda-worker/lambda-worker.test.ts
Allow queue event source to be enabled or disabled on the queue worker. This is an optional property `enableQueue` that defaults to true if unset.
=> feat: expose enable queue prop for disabling of queue worker

lib/authenticated-api/authenticated-api.ts
Exposed so can be referenced from stacks that consume the construct.
=> feat: expose api and httpapi ids for authenticated api

.circleci/config.yml
Issue: https://github.com/talis/platform/issues/5204
In https://github.com/talis/talis-cdk-constructs/pull/28 we added a `be_kind_to_your_colleagues` to the build. However, the repo this was copied and pasted from still uses `master` rather than `main`. This was not picked up in the copy/paste.
This has resulted in the `be_kind_to_your_colleagues` step running on the build after the merge to `main`.
This PR therefore renames `master` to `main` in the circle build.
=> fix: main branch not master

examples/simple-authenticated-api/lib/simple-authenticated-api-stack.ts, examples/simple-lambda-worker/lib/simple-lambda-worker-stack.ts, lib/authenticated-api/authenticated-api.ts
https://github.com/talis/platform/issues/5272
The destroy stacks steps in the build are taking 20 minutes plus. This is due to the creation and destruction of a security group.
This PR changes the example stacks deployed in the build to use an imported security group - therefore significantly reducing build times.
Note: This PR only fixes the first issue with the length of the build. Having fixed this, the tear down of the simple lambda worker stack is much reduced. However, we have another problem with the authenticated api construct which we are still  investigating.
=> fix: reduce build time by importing security group

examples/simple-authenticated-api/package-lock.json, examples/simple-authenticated-api/package.json, package-lock.json, package.json
Changes the package reference for talis node to use `https` protocol over `git` protocol due to brownout caused by https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> fix: change reference for talis node package

.gitignore, lib/cdn-site-hosting/cdn-site-hosting-construct.ts, lib/cdn-site-hosting/cdn-site-hosting-props.ts, test/infra/cdn-site-hosting/cdn-site-hosting-construct.test.ts, test/infra/cdn-site-hosting/cdn-site-hosting-with-dns-construct.test.ts
Apps that rely on client side routing will return a 404 when going to a page other than `/`, this is because that url doesn't correspond to a file in the S3 bucket. 
For example, in Otis going to `/talis/player` would return:
whereas what we want is:
This PR adds in support for a new option called `isRoutedSpa` that's off by default, but when enabled it configures a custom error response in CloudFront so 404s from the backend are replaced with a 200. It also tweaks the S3 configuration to not set an `ErrorDocument` since this should only be needed for SPAs.
=> fix: adding in a custom error response so we get 200s instead of 404s

lib/aspects/resource_prefixer/cfn_resource_prefixer.ts, lib/aspects/resource_prefixer/prefixers/apigatewayv2_cfn_api_prefixer.ts, lib/aspects/resource_prefixer/prefixers/apigatewayv2_cfn_stage_prefixer.ts, lib/aspects/resource_prefixer/prefixers/dynamodb_cfn_table_prefixer.ts, lib/aspects/resource_prefixer/prefixers/ec2_cfn_security_group_prefixer.ts, lib/aspects/resource_prefixer/prefixers/iam_cfn_role_prefixer.ts, lib/aspects/resource_prefixer/prefixers/index.ts, lib/aspects/resource_prefixer/prefixers/lambda_cfn_function_prefixer.ts, lib/aspects/resource_prefixer/resource_prefixer.ts, test/fixtures/infra/aws-ec2/cfn_security_group.ts, test/fixtures/infra/aws-iam/cfn_role.ts, test/fixtures/infra/aws-lambda/cfn_function.ts, test/infra/aspects/prefixers/ec2_cfn_security_group_prefixer.test.ts, test/infra/aspects/prefixers/iam_cfn_role_prefixer.test.ts, test/infra/aspects/prefixers/lambda_cfn_function_prefixer.test.ts
Refactored the CfnResourcePrefixers to use an abstract base class and add prefixers for the following:
- CfnSecurityGroup (aws-ec2)
- CfnRole (aws-iam)
- CfnFunction (aws-lambda)
This extracts the work done on https://github.com/talis/talis-cdk-constructs/tree/sm08_add_lambda_prefixer
=> feat: refactor cfn prefixers and add lambda prefixer

lib/aspects/resource_prefixer/cfn_resource_prefixer.ts, test/infra/aspects/resource_prefixer.test.ts
AWS expects names to be 64 characters or less, this updates the prefixer aspect to truncate names longer than 64 characters when using logical ID for the name
=> fix: truncate prefixed name to 64 characters

package-lock.json, package.json
* talis/elevate-app#5228
Otis and Elevate report a security vulnerability in Lodash that comes from a dependency of this repo.
This vulnerability was fixed in `talis-node` here: https://github.com/talis/talis-node/pull/29
Updates the version of `talis-node` to `v0.1.9`.
This version has an upgraded version of Lodash which resolves a security vulnerability.
=> feat: ele-5228 update talis node version to latest

examples/simple-authenticated-api/lib/simple-authenticated-api-stack.ts, examples/simple-lambda-worker/lib/simple-lambda-worker-stack.ts, lib/authenticated-api/authenticated-api-function-props.ts, lib/authenticated-api/authenticated-api-function.ts, lib/authenticated-api/authenticated-api-props.ts, lib/lambda-worker/lambda-worker-props.ts
- https://github.com/talis/platform/issues/5576
This PR makes the VPC optional for both the Lambda Worker and Authenticated API constructs.
It changes the examples to not use a VPC, but leaves how you would do so as an example comment.
=> feat: plat-5576 make vpc optional in api and worker constructs

examples/simple-authenticated-api/lib/simple-authenticated-api-stack.ts, examples/simple-lambda-worker/lib/simple-lambda-worker-stack.ts, lib/authenticated-api/authenticated-api-function-props.ts, lib/authenticated-api/authenticated-api-function.ts, lib/authenticated-api/authenticated-api-props.ts, lib/lambda-worker/lambda-worker-props.ts
Reverts talis/talis-cdk-constructs#48
This PR reverts the previous PR to make VPC's optional. There is nothing wrong with the PR itself, however because it only had one commit, github's did not need to squash the commits when it was merged. This means it did not used the PR title as the message for the squash commit. The commit message on the branch does not conform to conventional commits. This meant that no version was released:
Merging this PR will still fail to create a release, because the single commit comment created by github when you hit the revert button also doesn't comply with conventional commits.
After this is reverted - we can revert the revert and add a second commit, which will create a PR which will trigger a release.
=> chore: revert "feat: plat-5576 make vpc optional in api and worker constructs"

package.json
We have converted the authoeriser function from javascript to typescript. The distribution only contains the compiled javascript file.
This has caused an issue that the authenticated api construct is referencing a `.ts` file. When this library is pulled into another project, the `.ts` file is missing.
We discussed various options:
- compiling the .`ts` file ourselves rather than having the AWS CDK  compile it.
- pulling the authoriser code out into it's own repo so it could be include in projects directly
- deploying the authoriser function as a service
- moving to the jwt approach we want to get to now, which would require persona changes
- adding the `.ts` file to the distribution
The decision was that we want to move to the jwt approach, but we can not do that right now. Therefore add …
=> fix: plat-5537 add authoriser.ts files to distribution

lib/cdn-site-hosting/cdn-site-hosting-construct.ts, test/infra/cdn-site-hosting/cdn-site-hosting-construct.test.ts
When deploying assets to S3 via CDK, ensure the order of the sources given in config is honoured.
This allows routed SPAs to explicitly deploy the `websiteIndexDocument` last, after all other assets have been deployed, avoiding any downtime caused by the `websiteIndexDocument` pointing to missing assets.
- See https://github.com/talis/elevate-app/issues/5746
=> feat: honour cdn-site-hosting source deployment order

.circleci/config.yml, .husky/commit-msg, package-lock.json, package.json
- This relates to talis/platform#5578
This P/R achieves the following
=> chore: re-enable commit linting

examples/simple-authenticated-api/lib/simple-authenticated-api-stack.ts, lib/authenticated-api/authenticated-api.ts
- https://github.com/talis/platform/issues/5577
This PR makes the `domainName` object a read only attribute from the API construct.
This is needed for Smalti which is using the regional domain name and the regional hosted zone id.
=> feat: plat-5577 api construct exposes the domain name

lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/lambda-worker.test.ts
- https://github.com/talis/platform/issues/5879
This PR fixes an alarm on the LambdaWorker.
The alarm for the age of the oldest message was incorrectly on the LambdaWorkers DLQ rather than the main queue. This PR moves it to the main queue.
There are tests for this alarm - but they were checking that the alarm was created on the DLQ. The tests have therefore been updated too.
=> fix: plat-5879 - correct alarm on lambda worker

lib/cdn-site-hosting/cdn-site-hosting-construct.ts, test/infra/cdn-site-hosting/cdn-site-hosting-construct.test.ts
- https://github.com/talis/platform/issues/5908
We have started seeing deployment errors in CA:
These are not happening in the EU region for the same deployment.
We believe the error is being caused by the creation of the bucket taking longer than it has in the past, and the construct starting to sync data with the bucket before it has been created.
This PR adds a dependency to first of the file "deployments" on the s3 bucket, to ensure it is created before the first deployment starts. The other deployments are chained together, with each deployment having  a dependency on the previous one. So these will also not happen before the bucket is created.
=> fix: plat-5908 add dependency to cdn-site-hosting construct

lib/cdn-site-hosting/cdn-site-hosting-with-dns-construct.ts, test/infra/cdn-site-hosting/cdn-site-hosting-with-dns-construct.test.ts
- https://github.com/talis/platform/issues/5918
Apps using the `cdn-site-hosting-with-dns-construct` are leaving behind acm validation records in Route 53.
Previously, the construct creates a DNS record, which is itself destroyed when the cloud formation stack is destroyed, however, this process also creates an `acm.validations.aws` route 53 entry outside of the cloud formation stack. This is the record which is never deleted. 
This PR adds an optional certificate to the `cdn-site-hosting-with-dns-construct` props. This will allow applications using it to specify an existing certificate which will not be created and deleted as part of the stack. Doing so will stop the `acm.validations.aws` record from being created in the first place and nothing will be left behind.
=> feat: plat5918 make certificate optional for cdn-site-hosting-with-dns-construct

lib/talis-cdk-stack/talis-cdk-stack.ts
- https://github.com/talis/platform/issues/6457
On this PR the tags are applied now to the construct instead of to the app scope
from https://docs.aws.amazon.com/cdk/v1/guide/tagging.html
=> fix: plat-6457 tfs tags are added to the stack instead of the app

.prettierignore, examples/container-lambda-worker/container/Dockerfile, examples/container-lambda-worker/container/package.json, examples/container-lambda-worker/lib/container-lambda-worker-stack.ts, lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/image-assets1/Dockerfile, test/infra/lambda-worker/image-assets2/my.Dockerfile, test/infra/lambda-worker/lambda-worker.test.ts
* talis/platform#6511
* Allow creating LambdaWorker's Docker image via `fromImageAsset` - the image will be pushed to `aws-cdk/assets` repository. The image's tag is inferred from the hash of assets used to build the image as well as options used during the build.
=> feat: lambda worker - support container fromImageAsset

lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/lambda-worker.test.ts
We have been defaulting to 4 days for message retention on SQS queues in the LambdaWorker. This has been the same for both the main queue and the workers DLQ. 
This hasn't caused a problem - the LambdaWorker enforces having an alarm so we always get an alarm if there are messages on the DLQ in production and they are always dealt with in time.
However, in a none production environment recently, we left messages on a DLQ during the August holiday season, assuming the retention period was 14 days. They expired after 4 days. This was not a live environment, so no production issue occurred, but it highlighted that we are still using the default 4 days.
This PR increases the retention period on the queues to the maximum 14 days. There is no reason for this to be set to anything less - …
=> feat: increase lambda worker default message retention period

package.json
This PR fixes a problem with the asset zip file created version 3.0
The `files` section from the `package.json` was lost when the project was recreated as a CDK V2 project. This resulted in the wrong files being included in the github release asset zip file.
This PR restores the `files` section.
=> fix: plat-6742 restore package.json files section

examples/simple-cdn-site-hosting-construct/README.md
This PR updates the cdn site hosting example with details of best practice now we have a working example.
=> chore: update documentation for cdn host construct with example of best practice

examples/container-lambda-worker/lib/container-lambda-worker-stack.ts, examples/simple-lambda-worker/lib/simple-lambda-worker-stack.ts, lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/lambda-worker.test.ts
resolves: https://techfromsage.atlassian.net/browse/PLT-83
This PR adds support for maxConcurrency property in LambdaWorker (SqsEventSource)
=> feat: lambda worker - support maxConcurrency (SqsEventSource)

examples/simple-cdn-site-hosting-construct/lib/simple-cdn-site-hosting-construct-stack.ts
[PLT-801](https://techfromsage.atlassian.net/browse/PLT-801)
Update talis.io certificate ARN to point to the new certificate.
[PLT-801]: https://techfromsage.atlassian.net/browse/PLT-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update talis.io certificate

lib/authenticated-api/authenticated-api-function-props.ts, lib/authenticated-api/authenticated-api-function.ts
* [TA-1105](https://techfromsage.atlassian.net/browse/TA-1105)
Whilst working on the new bookmarking extension API, we need to include `jsdom` in a lambda function. `jsdom` does not bundle correctly and requires extra options to help this along. Currently the `AuthenticatedApiFunction` does not expose the CDK bundling options.
* Expose the bundling options for an `AuthenticatedApiFunction`
[TA-1105]: https://techfromsage.atlassian.net/browse/TA-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ta-1105): add bundling options to authenticated api

lib/authenticated-api/authenticated-api-props.ts, lib/authenticated-api/authenticated-api.ts, test/infra/authenticated-api/authenticated-api.test.ts
* [TA-1696](https://techfromsage.atlassian.net/browse/TA-1696)
**Description**
talis-cdk-constructs hard codes the value of the CORS header `access-control-allow-credentials` to `true`. We have a requirement in the new extension to wildcard `access-allow-origins` however, when `access-control-allow-credentials` value is true, AWS API Gateway will not allow you to wildcard the origins. We therefore need to be able to set `access-control-allow-credentials` to false so that we can wildcard the origin.
[TA-1696]: https://techfromsage.atlassian.net/browse/TA-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(TA-1696): set cors allow credentials optionally

lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/lambda-worker.test.ts
https://techfromsage.atlassian.net/browse/PLT-1141
Problem:  when replaying messages in bulk, the number of concurrent lambda’s are not controlled and this can result in a flood of concurrent lambda’s
Solution: We set the max concurrency on the lambda workers SQS trigger for the main queue. We should set the same value on the DLQ trigger.
=> feat: set maxConcurrency on LambdaWorker DLQ

examples/simple-cdn-site-hosting-construct/lib/simple-cdn-site-hosting-construct-stack.ts, lib/cdn-site-hosting/cdn-site-hosting-construct.ts, lib/cdn-site-hosting/cdn-site-hosting-props.ts, test/infra/cdn-site-hosting/cdn-site-hosting-construct.test.ts
- https://techfromsage.atlassian.net/browse/PLT-1403
In order to make a consumer of the CDN Site Hosting Construct (OTIS) TLS 1.2, this PR allows the security policy protocol to be set.
So the behavior does not change, the default remains `TLS_V1_1_2016` but this can now be overridden in the props.
The Infra Unit tests now check for the minimum TLS version.
The integration tests deploy cdn site constructs which both have the default and override it.
=> feat: make securityPolicy configurable on CdnSiteHostingConstruct

lib/authenticated-api/authenticated-api-function-props.ts, lib/authenticated-api/authenticated-api-function.ts, lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/infra/authenticated-api/authenticated-api.test.ts, test/infra/lambda-worker/lambda-worker.test.ts
`nodejs18.x` Lambda runtime is going to be deprecated on Sep 1, 2025. To make upgrades easier, we should allow CDK apps to specify their own runtime version, rather than imposing one.
This PR makes constructs that use NodejsFunction construct expose additional props: `runtime`, `awsSdkConnectionReuse`, `depsLockFilePath`, `bundling`, `projectRoot`.
These are non-breaking changes. For backwards compatibility, we're keeping `runtime` defaulting to `nodejs18.x`, and `awsSdkConnectionReuse` defaulting to `true`. However, it should be noted, connection reuse setting has no real effect where AWS SDK v3 is used. The `AWS_NODEJS_CONNECTION_REUSE_ENABLED` environment variable does not exist in the AWS SDK for JavaScript v3 but clients [reuse connections by …
=> feat: allow custom NodejsFunction runtime

lib/authenticated-rest-api/authenticated-rest-api.ts
- https://techfromsage.atlassian.net/browse/PLT-1355
In PR https://github.com/techfromsage/talis-cdk-constructs/pull/98 a new Authenticated Rest API was added.
Using the released version of the library fails because the construct is referencing the typescript file for the authoriser, not the javascript file:
```
Error: Cannot find entry file at /home/circleci/repo/node_modules/talis-cdk-constructs/lib/authenticated-rest-api/../../src/lambda/rest-api/authorizer.ts
```
This PR corrects the new construct to reference the built javascript file included in the release. This is in line with the other constructs, referencing the javascript file of source code, not the typescript file.
=> feat: correct authorizer include .ts -> .js

lib/lambda-worker/lambda-worker.ts
- https://techfromsage.atlassian.net/browse/PLT-1454
This PR exposes the main sqs queue for the lambda worker as a readonly public property. This is needed if changes are required to the queue. 
Previously it has not been exposed, so that unwanted changes could not be made, allowing the construct to enforce things like retention period and visibility timeouts. 
However, to use this worker with EventBridge, we need access to the queue to set up IAM Policies. We have decided to expose the queue so that the user can do this externally to the construct rather than implement a mechanism within the construct to support EventBridge. This does mean the queue is exposed and settings on the queue COULD be overridden.
We are not exposing the DLQ at this point in time. This is internal to the worker …
=> feat: expose main queue from lambda worker

lib/lambda-worker/lambda-worker-props.ts, lib/lambda-worker/lambda-worker.ts, test/infra/lambda-worker/lambda-worker.test.ts
- https://techfromsage.atlassian.net/browse/PLT-1759
This PR allows the overriding of the default value of the Lambda Workers queueTimeout property. 
To fix issues at scale with triggering lambda's from SQS, the lambda worker previously enforced a queue timeout following guidelines described here:
- https://zaccharles.medium.com/lambda-concurrency-limits-and-sqs-triggers-dont-mix-well-sometimes-eb23d90122e0
AWS later provided a fix for this issue, the setting of a `maxConcurrency` setting described here:
- https://aws.amazon.com/blogs/compute/introducing-maximum-concurrency-of-aws-lambda-functions-when-using-amazon-sqs-as-an-event-source/
`maxConcurrency` was made a **MANDATORY** property on LambdaWorker in PR:
- https://github.com/techfromsage/talis-cdk-constructs/pull/86
This PR allows …
=> feat: plt-1759 add optional queue timeout property to lambda worker
